services:
  web:
    image: zaza_interior:render
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/home/app/web/static_files
      - ./mediafiles:/home/app/web/mediafiles
      - ./locale:/home/app/web/locale
    platform: linux/amd64

