services:
  web:
    image: zaza_interior:render
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "80:80"
    env_file:
      - ./envs/.env.render
    volumes:
      - ./staticfiles:/tmp/zaza_interior/static_files
      - ./mediafiles:/tmp/zaza_interior/mediafiles
      - ./locale:/tmp/zaza_interior/locale
      - ./db:/home/app/web/db
    platform: linux/amd64

