services:
  web:
    container_name: zaza_app_web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env.dev
    volumes:
      - ./staticfiles:/tmp/zaza_interior/static_files
      - ./mediafiles:/tmp/zaza_interior/mediafiles
      - ./locale:/tmp/zaza_interior/locale
    platform: linux/amd64
    command: bash -c "gunicorn zaza_interior.wsgi:application --bind=0.0.0.0:8000 --workers=$((2 * $(nproc) + 1)) --timeout=120"

  nginx:
    container_name: zaza_app_nginx
    image: nginx
    restart: on-failure
    ports:
      - "127.0.0.1:81:80"
    volumes:
      - ./staticfiles:/home/app/web/static_files
      - ./mediafiles:/home/app/web/mediafiles
      - ./locale:/home/app/web/locale
      - ./nginx/dev/conf.d:/etc/nginx/conf.d
      - ./nginx/dev/logs:/var/log/nginx
    depends_on:
      - web