services:
  web:
    container_name: zaza_app_web
    image: zaza_interior:prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env.dev
    environment:
      - GUNICORN_WORKERS=10
      - GUNICORN_RELOAD=true
    volumes:
      - ./static_files:/var/www/zaza_interior/static_files/
      - ./mediafiles:/var/www/zaza_interior/mediafiles/
      - ./locale:/var/www/zaza_interior/locale/
      - ./db:/home/app/db/
    platform: linux/amd64

  nginx:
    container_name: zaza_app_nginx
    image: nginx
    restart: always
    ports:
      - "127.0.0.1:81:80"
    volumes:
      - ./nginx/dev/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx/prod/custom_pages/50x.html:/usr/share/nginx/html/50x.html:ro
      - ./nginx/dev/logs:/var/log/nginx
      - ./static_files:/var/www/zaza_interior/static_files/:ro
      - ./mediafiles:/var/www/zaza_interior/mediafiles/:rw
      - ./locale:/var/www/zaza_interior/locale/:ro
    depends_on:
      - web